#dbeaver adjust column length
SELECT
    TENANT_ID, 
    TABLE_SCHEM,
    TABLE_NAME,
    COLUMN_NAME,
    COLUMN_FAMILY,
    COLUMN_SIZE
FROM SYSTEM.CATALOG 
WHERE 
    TABLE_SCHEM='PHM' 
AND TABLE_NAME='DELTEST01'

UPSERT INTO SYSTEM.CATALOG (
    TENANT_ID, 
    TABLE_SCHEM,
    TABLE_NAME,
    COLUMN_NAME,
    COLUMN_FAMILY,
    COLUMN_SIZE)
VALUES (
    null,
    'PHM',
    'DELTEST01',
    'FAC_ID',
    '0'
    200)


#dbeaver adjust key seq
SELECT
    TENANT_ID, 
    TABLE_SCHEM,
    TABLE_NAME,
    COLUMN_NAME,
    COLUMN_FAMILY,
    KEY_SEQ
FROM SYSTEM.CATALOG 
WHERE 
    TABLE_SCHEM='PHM' 
AND TABLE_NAME='DELTEST01'

UPSERT INTO SYSTEM.CATALOG (
    TENANT_ID, 
    TABLE_SCHEM,
    TABLE_NAME,
    COLUMN_NAME,
    COLUMN_FAMILY,
    KEY_SEQ)
VALUES (
    null,
    'PHM',
    'DELTEST01',
    'EDC_ITEM',
    '0'
    3)